// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zzx7kGjgPN7_jaEI0zyqhkFL1VBWmcE',
    appId: '1:776670623415:web:bf031f6fc04ac771dd7f32',
    messagingSenderId: '776670623415',
    projectId: 'smartlockproject-arduinouno007',
    authDomain: 'smartlockproject-arduinouno007.firebaseapp.com',
    storageBucket: 'smartlockproject-arduinouno007.appspot.com',
    measurementId: 'G-ZEDMFMKFG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqANmcjoBMCq2OMv7Kafbmwtm9nA94sgU',
    appId: '1:776670623415:android:37906cc304fdef28dd7f32',
    messagingSenderId: '776670623415',
    projectId: 'smartlockproject-arduinouno007',
    storageBucket: 'smartlockproject-arduinouno007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrXYaydJNK3XcB1V2Dvh4HlCxu0SPovU',
    appId: '1:776670623415:ios:92ebe7b24ee61757dd7f32',
    messagingSenderId: '776670623415',
    projectId: 'smartlockproject-arduinouno007',
    storageBucket: 'smartlockproject-arduinouno007.appspot.com',
    androidClientId: '776670623415-utehvau2pju6css2e5psfsagf937qtk0.apps.googleusercontent.com',
    iosClientId: '776670623415-vma9q8sas1hqfhamj5077l0kmef7n414.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLockSystemOnArduinoUno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcrXYaydJNK3XcB1V2Dvh4HlCxu0SPovU',
    appId: '1:776670623415:ios:92ebe7b24ee61757dd7f32',
    messagingSenderId: '776670623415',
    projectId: 'smartlockproject-arduinouno007',
    storageBucket: 'smartlockproject-arduinouno007.appspot.com',
    androidClientId: '776670623415-utehvau2pju6css2e5psfsagf937qtk0.apps.googleusercontent.com',
    iosClientId: '776670623415-vma9q8sas1hqfhamj5077l0kmef7n414.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLockSystemOnArduinoUno',
  );
}
